language: python
python:
    - 2.6
    - 2.7
    - 3.3

script: py.test

notifications:
    email:
        on_success: never
        on_failure: never
branches:
    only:
        - master
        - develop
