language: python
python:
    - 2.7.6

script:
    - python setup.py build
    - python setup.py test

notifications:
    email:
        on_success: never
        on_failure: never
branches:
    only:
        - master
        - /^release-.*$/
